---

- name: preflight | include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yaml"
    - "{{ ansible_os_family }}.yaml"

- name: preflight | define path for curator script file
  set_fact:
    curator_bin_path: "{{ __curator_bin_path }}"
  when: curator_bin_path is not defined
